passwords:
    root: ENC[AES256_GCM,data:rNpxcMf6SlcMKG21SctGi2wLi3R7EpYhEeGH95ZW71FHqUoi3Tsv1NzaohdHzLTn3kps215WUD6/Dc8pplt9VvqMDi6vq7xvHg==,iv:3P2uDNelJS1SfDnCf1Jlu1jaGiv5u5kJHguwC5J+ksw=,tag:IX7zHta4cYANxhDafiDK1w==,type:str]
tokens:
    spotify-client-id: ENC[AES256_GCM,data:MCfdTYPrZEhKjVHYfM4ryNf2yEkbEqYPe0xcJGQ2unw=,iv:qtV7V9UqxfZBYa+iMKGMfSiE8M37kaR6QURmJPBBmTk=,tag:gXBCnjmAOCW3qsFXaUj2YA==,type:str]
sops:
    age:
        - recipient: age1j4yy6e7x783c83n3lxvd5fzwlpevnm0fnznmlrg0asawudjfyd0q0664yu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeXRZcFJjRFU4eGU5d3pw
            ZHNSeERzMkR3YldtQlp6dUw4VlBQR1Vhb2c0CmZqQzRxL1BvYkxOWUk2ZmJnQi9z
            L1duUjdGaTFvdWNhWlFLbjlNWkMzcUkKLS0tIFZUa1o1THN2VEp6dHdGQ3JwNXc5
            S200bkNXeGppVzU4Nkc0UXR5a3FvNVEKA/5UKCzdmmt+mFoFOFSNB4eMbSGN2bG/
            IPEGHuqNtvc4mrNh3Rm/C6TgMdXd2qLZRib/TP60MPQv7WPaIu7Tzg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1359480kd4q88mq3n3hgas9j29xle7slnm8d7jnut233xmkycpg7sefv9wf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtajZiVWQ3L1JUZVJjZ0VB
            RTBwZEN3U0NHWmNHekorcjRHWjZJV29MUmpnCnlKMlBlcnFkMzl1SjI4N2t5ek1m
            VnlzTjFuRGh6MmQ2NjdtUVVsR2MxRG8KLS0tIDRhRFljTk15akhXU09vdHZVWmZR
            bkp4VjJ0MnJEc29sUFZ2ak5SUmRZeWsKWG8DE0QT31Gatro8oGvpSZD0KwqlE/oC
            eDOeWrO27oU0rFHaw+Uoql0K13bpwjl9LR3uvK/j+hB8TViPRuddjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T12:16:50Z"
    mac: ENC[AES256_GCM,data:lkk4s12BK5EMamYYKFq4bXmuJQRPVMye9Mfpj92AdgwtAmKCvXvZtCCJNVKWcW62X3v9Yoc4oxOp3Mo5mtCRFqRrcG4WXZZGUtCu2xs9KoLi8D2FldqCFX8HtNefDGKLLZ7iTBAFwb8zBwniCI4zjc1URKDuTWiQoseWKwo+bt4=,iv:P0lqqttO1wYkmApkgkE/lBGHXf1G0N8IzTYKsvt+JXY=,tag:abakuOqUsbA73f6yJrKLCQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
