auth: ENC[AES256_GCM,data:SwBlInd01Hw2bFkKe95zrgiIzRZKo3r1g7B4ZltubDQeadrTGrnhoTxTuuDjO1Sf9IvUz9z+3osF+C5PefzfF0SvWLQiYQFOKIdJtFbmtGcoeylt6IRjIrIvLgz0gZ0evH407Kf2b7R7LL0MTl/+W/VQlKNQihPnxCTHnKgu7M/4cOwv23fwGzyJkA9vxCY8wZUfu4EPYbDvOd7VCE0mdAm96P5p64re/zVhX8lG7AowEbCHNGYmQNj4l2IwZntGGet+8oUOZJyz0vAT9d9xQsBX+s5FacuJqyi4c+KO+IBcqwO+XV3TsSRqNz4kDIEQEzmZvuxe55L3BnYJznGaHMIZiKwkRQ1a9qtMZX2APZk5WfUCleQsUTqYFomqG00ooQ/7dfxaTsfANkiJafbh3kS0tJtkcA/ooClfXVfN0K49TK9WReVdESIZ/xH9EMP7NUI43Ya72hC88sIbfllRMnZ+gfISJfFWZr8RuQ4l1y+ML2GR7+EChzpbKqB//jevIBR9zRvVpULIJc8pNlURSbsNX+IUk/z8npL6BTcQCz3U7gGtKOpY8f5yUcA0bXrhUow3bG3Nl/wjBdK52NuIuE+yV2TTWX33NMvX/T0Xqis=,iv:A99mPSsTSpsGUGO1grXqVYtBRa9ED3hPZkV6SWVR/Kg=,tag:cIICHx3v+/eX6sJfvoDrEw==,type:str]
sign: ENC[AES256_GCM,data:UglMeDD9skgsjg4nSHzrD6qNg7rZ+J+wn6fMGj0UU9pAHzxPwK0ETD5IX7BnCPgU1zOoj6nX4g9N8cE9TBGycCD0qgJqiO7O0HIfcs0qUjIKDZxIaXGJ0uD+xB45YBaAkKphFI+B/3ghAC32CAryYwu+dDmi9LtxQBTLXVbHTCF7sr2g2gkyig3HYhAv+Tyi6ljIPLOQ3cxXna3hLZ/602Gc9vCoW3GjLOrxGEorBEtr9e73jFY2CzD8fj+9g5kxp6b3HNF/kKlsutSN4X4JjJOVxke3MlJz1lX2xFemo9+P6PNL49YctYJ0jHJabOJyOwaZQ1/mtsGlSgmKnZ7Jj7bIFzMESUJ57s4SFiRacMtoFCYqHriqEL8nijAbt6o9XEWbuLHnXMK9gdH4LeFvwScZnHvc4ifkCsvbRua5S9hlci69W97JYxNq/1Z3VYWdSV3qoRGNBW1tOLNTEIe+5wYvP9tToyUc/4ppNyz0su+DEk51GjkxXsE7T+Lg8oZM1/+m99H7TkbHuflqW3gn8SqWrtuOjwOEXv7ukYq09jzh6Z62bZ0nouAMtQQ84Q2gWE7u5SXSxCIiwQdS/lNrN2694AAOSnkLslKPCEjY4yQ=,iv:cxITGkCKnyvFclKWfhamblnpN3hAHWMi6TZDQOP616c=,tag:227H0cI9LbUbQgHEMQ+SQA==,type:str]
spotify-client-id: ENC[AES256_GCM,data:PXurtPBGFOkzK0yt68NPtUUbJr/tg+QUZvAzGuPsc2Q=,iv:M7fyyH2VAV0UN43jmdTv5Rk9thiW86xRTEn9CKEde1g=,tag:3rurY0lAgEbkI+qgxNvScA==,type:str]
sops:
    age:
        - recipient: age1m6mszkt83fdx63hqmlgkcc3jm2rtztvxr73fw8nwlk4sdqgh7quqqw5zl5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwT29oc1dsRElxTnNMK1lM
            L29PMFNRd0JyR2ZRdm5ZTzMvU2tMSmVJdGw0CktneVkzaWVlT2ZJWUVZRUs1Q1Bq
            RUp0azRwa3VqQURYWC9mZFVqY2hNSmsKLS0tIEM5THRJQ3hZWHpLNTRONUFqQi8w
            UzdqQ1k0ZnQvTFg5akNvc3FXNStOK28Ki6ZRWHfVgRYta7X/nOJekh7n8LhN1IYK
            T2WRK25WMlgFgZQr67e5LklGfqiFMbTsBUhig44SfLrJVbeB89uPuQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1359480kd4q88mq3n3hgas9j29xle7slnm8d7jnut233xmkycpg7sefv9wf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibmZRQ05SbWtBZjhQR2NM
            M0RCb0p2eWtydmxCTENmbWF4NVJaUGZmb1J3Cm40OEYvZklabnVsS2NZQUxhUnB5
            cXVPendvQ1Z5Yklsbkpjb0N3WitoQUkKLS0tIDJPWXdybE54dVMzMUl2aCswS0R3
            dkw1UktqYUFueXNyZjhRN3FSdHZGMzQKEsMLft01Uy0PI5J4SgqQeaLHFl7+/q5F
            NDRXFEaH0zlCmsayqgeXO/s6LFjvQ7TBXQQHKNAcVD55zz0J3XTbhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T11:14:50Z"
    mac: ENC[AES256_GCM,data:GAoLe7Dp4STJPzVviujh8DVy9ydgoX/GPMCQmJkMIL+q8mvRFf6o9vT1NwOH5zuwzaAC61vrhwbzavIVN60nzRpm/S0UoOa+3g+bTWv2wb1bFunnLQZ+Ns4hXYQdPJg5tqw6d0Imuv6q8BTidyFIJDCpMONhM4BpPgEibraMCHU=,iv:Fr7l0tBZjQoZaMesmjJXHL8fZ4DIJGgCIqrivt6HCM0=,tag:SY9g2raTavFZkDNZ4+rXKA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
