auth:
    public: ENC[AES256_GCM,data:BV4J9lG2MrwFCNaI9ymjoLFt8xo4idrcqkd/xQPv7Xz5kM0E7HO8Dy3YbYErbgSCpxtt50pqL/wfc7OS4eoJfI1uBia2leB1yePWyyeNZi/e8NxGrOIelgiUKUuGpi7D,iv:kcLBBbs+tJxj0xgWebztPSRSFpd34A2rYxdy/hS0u/4=,tag:ZvQ3T1G7BLz3+DGgeI1Vrw==,type:str]
    private: ENC[AES256_GCM,data:CtLYJQkYv+on39DbWXEuHrRds3otAVG3oTrLdUizLSmywXRXHVx4yKU5YbyMMq0xO9Kzx+KcNCS6Lw9tACux5KmmS+1uutUzAUWrzWV5V2/xfUXxO+ZFVd2UF9680rOJ5m3jkB/bJTYdy02XMmrKbijzgoF+KAqnciQ/psS3ZLx/KzHTwmcv3KY7t+Pjk2nYuoAKRdTskl3hFAUueNJ2z0A2ucgneEZkxLUeYNQ41wfqHM3d0G/n4yrdphs/1N+ptBSmOwap1Z/l7RrSyIGe0vjuonKK+CAo4S3GoXGu2aI3H5/79H/uNSUt9DXddfZgfQFpUE0DhhxhKrSHlWDz7R6BMylpqrl6eCz6fLk1tgEtUP2ULyS7VSLjMFT4YnUTPPYveKn5WAmO0KZYMRjanIDwapsNkIzTO8GTot8qS72mP9L2Oxkj5tIFPDqCBF1eo37wupQiZbcbvoKz71ozlLcCNPu3NVUg/PALu/60RNMue2KjUOeErgmASj7J6KO7VF5WamvRuc5CC05m+1ZWDUaZkbpq7QnljNp5pKzumCT649T9MW2vdOvOKtze6IZzV5WIMh8m2cvOscLDPcyWZypBR9y8LFJbVRRozftun+Q=,iv:hcwjAgGih+5W/AznAaw2vb3D+BeFetQkQYt2mEmLtaY=,tag:nMIkA8wAUtdwTdP5Ai3jiA==,type:str]
sign:
    public: ENC[AES256_GCM,data:m+59MungrvmMrF7R6YdBN7AURuhrjF8V21wgenUVmXamfCBJ2vcvWz19pU2/fr/jh9gok724qtFCy8lKTUdnwUdhxlj120KOtS2pYUhpEh9zVLLYqRc/FN3msqojU+Hk,iv:t1ozZ9ZB534aehzG2i+Hz3IDbNn4s2af0R4pAYHIrCs=,tag:maTpeSKw87pY8sBm5nTAIA==,type:str]
    private: ENC[AES256_GCM,data:HZRG/bmsOTmwNJnEfAaxX9yC+dj4IM3ZcgxxCBdrahbboFgMGhgqgX5mQ7vVlvDi02tkqDU2tD9GFb5XMR+A4v99G19l7LIFUPrIrgKc8Dcm+DkMFQqCz93/EOd6iWtbeTmn82kLa+7Due5gSj53LZEY8or941s0XA/tixCOpGnLmaGfpd2ri3kxFhg45kIAVBoebgjXBbPCdGyh10ymglwcyfKDUSVo28t6mgvtuWLmvx1ixtSEWB5M4I8PuULX5k1SyTn67hcSwtHH7T7g0wUuJ7xAWtT6foHDMGWSxJMY0q00/yQmxkOZB0qszeWjyzS8X0NoPfBMKC27CwLg6dnaJS/NxmIBnkGEzBc68aSuGZZFt6PTztIQpWa9OwFTqqK34cNVXWYCYRAM2TCH6Sf1ruagqDTaEmjczM8s6qgc3h2iDwgHymi/49R00er82u/sIRG49xKP8TZUI97CPLnMzhH/w+EBZ1jBKR0ncIKgXUY4eiSvImHB0N7rG1oTzLQFGDRsHogMZjlolBNjqXEYyM/zRAl18GhSbdMRO5dGulUzvWMh2nGMC0NkhjvvK/tHkxdhnjTwKtU3J/q9/ZTN67RA1Fc08O28bTipH3w=,iv:PnLelqtJuWVz+csGGRRqFdSzKgRhtr4o1v3giseaecQ=,tag:fJZDHBFTNFs7nB60EhgQrw==,type:str]
spotify-client-id: ENC[AES256_GCM,data:PXurtPBGFOkzK0yt68NPtUUbJr/tg+QUZvAzGuPsc2Q=,iv:M7fyyH2VAV0UN43jmdTv5Rk9thiW86xRTEn9CKEde1g=,tag:3rurY0lAgEbkI+qgxNvScA==,type:str]
sops:
    age:
        - recipient: age1m6mszkt83fdx63hqmlgkcc3jm2rtztvxr73fw8nwlk4sdqgh7quqqw5zl5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwT29oc1dsRElxTnNMK1lM
            L29PMFNRd0JyR2ZRdm5ZTzMvU2tMSmVJdGw0CktneVkzaWVlT2ZJWUVZRUs1Q1Bq
            RUp0azRwa3VqQURYWC9mZFVqY2hNSmsKLS0tIEM5THRJQ3hZWHpLNTRONUFqQi8w
            UzdqQ1k0ZnQvTFg5akNvc3FXNStOK28Ki6ZRWHfVgRYta7X/nOJekh7n8LhN1IYK
            T2WRK25WMlgFgZQr67e5LklGfqiFMbTsBUhig44SfLrJVbeB89uPuQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1359480kd4q88mq3n3hgas9j29xle7slnm8d7jnut233xmkycpg7sefv9wf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibmZRQ05SbWtBZjhQR2NM
            M0RCb0p2eWtydmxCTENmbWF4NVJaUGZmb1J3Cm40OEYvZklabnVsS2NZQUxhUnB5
            cXVPendvQ1Z5Yklsbkpjb0N3WitoQUkKLS0tIDJPWXdybE54dVMzMUl2aCswS0R3
            dkw1UktqYUFueXNyZjhRN3FSdHZGMzQKEsMLft01Uy0PI5J4SgqQeaLHFl7+/q5F
            NDRXFEaH0zlCmsayqgeXO/s6LFjvQ7TBXQQHKNAcVD55zz0J3XTbhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-08T20:17:30Z"
    mac: ENC[AES256_GCM,data:oNnDI0gn3e0997JkrfUnMk+rahKehmykTcDs61sC/i+a/nKe0UdSeIf4PitDS2mCbOqfIEfQsCq6RybXI1VbgMB2VXnf+5dmeQRl+uWLO6SzKT246CnlPGIpzSWyVpTk+39zT8B/edQ/TKP1SdvuGISRCIZD/u4yu4c7ytfTJ7M=,iv:jqIUqi0HAmLgZFkWAMQMe/MJoALpnQe0S0ncSZXWf4U=,tag:IO+rjBWPxj8kITfpae8j9w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
