passwords:
    root: ENC[AES256_GCM,data:OYv6r5NsxJrGl6+yj3kXe29JqBaXZm4Oe7u44wnB5ynEPUTaHPimbafYcPyHMTvhsPHi4z0PC6d8I7y3B2vCszaNYz1RuwwB0SZgbZ9Zm4J+a097p3BtsVWbmQbSyXbc4PQII8va+A23Gg==,iv:aKC1UFDmurjgtcgjfenMFSLgfrTsPZswWvqChUGLpew=,tag:uevJf5uElvsKQRfb6y4urw==,type:str]
sops:
    age:
        - recipient: age1c7hg9uvzq90xeugd7gvt77j38sea4mmukju3sd49a0h30ymgq9uqt7cw5z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aFJ4b0FrbHdCbzdWck05
            R2V0YUxTcVpDWVZXWVVvM3NnTHhxR2RtMkhvCi9YZ2N0QkIrQmwrNVA2TjMvamg5
            RXU3TWpPbXFmTzVJL2dPVVlBQXhGaUEKLS0tIFRIK0Fsd0hJa3p2RWgydGE1RzVQ
            MDM3M2hNSDhrNjlHTS9KYVozVndkazAK1orG6IMNI3GmobkU3Ep+TnRADj1Y2Awh
            XDshatC452CEcYIdavT4foHLsERQYBI3WEooylSKZa6SBZ/CT0g92A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1359480kd4q88mq3n3hgas9j29xle7slnm8d7jnut233xmkycpg7sefv9wf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUEI3NUgrcTVuYzI0T0dj
            czhOUkQ0WGRkOGtaTDBNa0JuUkJlR3BnZjNVCkR2bkR6ck1iOEJZNkFSSFZSZGVk
            UVVjWXpVaFg2T1Y4cVEzUVZFdFpBMnMKLS0tIGw3OTVHOFRNOEFGQjdiYTNZdjB1
            b1NsWncrY0JEeFdvZE9ZanhwQUlhbEkKT2FWTXd+8vF0nLyJSB8JCek6wxf9r3ZS
            mO+zlPxWK1eDFDfJDAp29AX9YomeQMM/8R/G4WCVmJaRtp1GzW5DHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-24T21:28:58Z"
    mac: ENC[AES256_GCM,data:5qvmUMZgBk1B3SCjkLV24J7FLoNK5AxyHXLtLmgXJyylayG5UVRooiLc5c/V4QbDE8ZqAEIp5T0FeiMCQpoEXnT7pFh5oc3MpvgbveeTOoHoKRA0srJEBYhDSDErG1nT2HAhuuNg0cs9sg66PGKeS6Dxo2IgMI2PxHGyLIaLOSQ=,iv:hoJ6gvr3pupav07yh+fukMpzYXpcfic2n+w0QAiJ5z0=,tag:m3OA4j4EXhB77h6jW2eleQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
