passwords:
    root: ENC[AES256_GCM,data:cC0jSLFG3XAH6vS817Bfi34zh+NcAEq207uJyUD+1t/dIBlybIQ9xhEEjOdkNJVST+1z29BymrBx57pioMcyHaKG2eVuCv3kGg==,iv:q2ttGZJQwGHdywRFgGyJm7CwKFtk/tvM0+V+7GkSxps=,tag:uDeW2BJBlgfOQFyzi48dcg==,type:str]
tokens:
    spotify-client-id: ENC[AES256_GCM,data:yfG4TojVwwsOtldqcPVu7ecZf+B4UVxa1Khh79jVTPA=,iv:yYNC4WNPqNoC2Uuv5rRA0AbbVMprh53q+we9Ue5jW2Y=,tag:ZqAR7iNzIjol/7ndozbtLA==,type:str]
sops:
    age:
        - recipient: age1c7hg9uvzq90xeugd7gvt77j38sea4mmukju3sd49a0h30ymgq9uqt7cw5z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aFJ4b0FrbHdCbzdWck05
            R2V0YUxTcVpDWVZXWVVvM3NnTHhxR2RtMkhvCi9YZ2N0QkIrQmwrNVA2TjMvamg5
            RXU3TWpPbXFmTzVJL2dPVVlBQXhGaUEKLS0tIFRIK0Fsd0hJa3p2RWgydGE1RzVQ
            MDM3M2hNSDhrNjlHTS9KYVozVndkazAK1orG6IMNI3GmobkU3Ep+TnRADj1Y2Awh
            XDshatC452CEcYIdavT4foHLsERQYBI3WEooylSKZa6SBZ/CT0g92A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1359480kd4q88mq3n3hgas9j29xle7slnm8d7jnut233xmkycpg7sefv9wf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUEI3NUgrcTVuYzI0T0dj
            czhOUkQ0WGRkOGtaTDBNa0JuUkJlR3BnZjNVCkR2bkR6ck1iOEJZNkFSSFZSZGVk
            UVVjWXpVaFg2T1Y4cVEzUVZFdFpBMnMKLS0tIGw3OTVHOFRNOEFGQjdiYTNZdjB1
            b1NsWncrY0JEeFdvZE9ZanhwQUlhbEkKT2FWTXd+8vF0nLyJSB8JCek6wxf9r3ZS
            mO+zlPxWK1eDFDfJDAp29AX9YomeQMM/8R/G4WCVmJaRtp1GzW5DHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-07T12:17:18Z"
    mac: ENC[AES256_GCM,data:sP24EmthGIeps0jH5k6iX6JtrLQFaau5varXUzgFLyhSoWO8YST8BmQiq44rzxZGSgKq/AnVHmnaYcrXXVDpmxV4fr9n9sZvwbDs+VNX8qJOdVNMXo3G06dIpbxxx+L9fJpGkS32LeuR2N13/OLa8uliL+L2OeSB1hXkpK9A/Ak=,iv:LT0IIEQJ+Ryk3Ifs/jvcU4v2zL1jyTrT3e1dVmZZlrE=,tag:dykShQiYyldr+Ljy2tgevQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
