nix-github-token: ENC[AES256_GCM,data:Y+jaD79N+DmGp1a909gocMMDs3cLZGBhSgZ9Z4pnFqhJ/0V8jWbD76rx5L16WOvFyiogVYhnRlww5cVrWtfCOOWIK1Yx/7KeGS/YMrXSiqswTFU3W6AaFV8BPoWysvA4mjYLkBFvRkHTGYXJnjPuNhqK8tWjyEUP,iv:leQYWzgAsMacRImcPkmUWY2EykzfmkA2APndO4/TeYQ=,tag:pExB3bLiD+b5pjPNlVOJuw==,type:str]
passwords:
    primary: ENC[AES256_GCM,data:VGjohGR9/w/3HjZWZZ6G8DWk5z1wTvwrCXRr2zNOLmpRL9CjbloAy7dohaMx7NZzEy7Sqa4A9ZSvtSwVehYENcaW9LLtPG3YNjcmKohnryJ4Q5Z4DEH37aNs4wj3gJNWzYD4mUdStYHp6A==,iv:TVr3lKKT9TlJE1ZkYbvd3fGowZ8Mks8FTssp1gA5phs=,tag:QBb09wHPCc1JOTxGwOfwhQ==,type:str]
    root: ENC[AES256_GCM,data:DhoCTdhGUe/NazbAGi1Xs7DbJHjqNLiAMOSvEsPLQVHbxybjiSynkm5hwNZeZSBPhpAgfZXCU8b0eOaj7e/QPYMbigzHDSORkIjh6wMIpYm2CsgRtutpz95bMvLqZdI3srMiwTxNV7FOLQ==,iv:NglEXKKMQigjaNBih2RPzGs4Gg9rEru5oYuCqMxku2M=,tag:AS4Me3QDOkjxj2RYVBoaLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1clhd7uqgp3ej2vv3s40xccsskn0qhvgpasrkj6e4s6zn0ujl29zq7r795x
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISG9wRVpPamQwS0cyY2lM
            QkI3K1NyRTZ0dk45R1NVYUtOY0dGWi82R1E4CjVEYjR1MnVtQ0pWVXRMQUlmSk5V
            SlBYbDFlRmtFUWFPQm5uczZaM2h6VnMKLS0tIExMYzM0ams0VnNVb3o3ZHVETnRF
            L1htbUFXc3FnODEwa2pNck5lVmR2ZzgKyZo/bwrPulSB8kA6Kd2Pn8KQCQ4bkchi
            D2YYQK7MP/rXOsV21GrJdPnQ4RMPgXsTaAF0lZB9nDjpBVUuN9LfEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-27T11:03:38Z"
    mac: ENC[AES256_GCM,data:Xc7XWcvYkY31yrRTw0iLWXTvUFIS8KDzH2pQvOBbxBV6i2OSQWE5BQME0C4gt53eSoMBqDQiJlULqBhR3S4qEsySv17aWTSb0CHI2hPy+g9Acm/rKDvycoJ+M8/c5owFTat19Sr5gv9mZOns3vPvrfgUbqBPlj0MaPHZV+SLpaU=,iv:RRTNeVBASB+zG3VO0Pqq6b90M7Tgc1KsBb0T696IA78=,tag:0iLa/2+Mt+gyoXkt7UCeHA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
